### ISSUE TITLE
Deferred example doesn't work as intended

### ISSUE THREAD

**Issue by Kerollmops** [gfx-rs/gfx#1010]
Excuse my french...

![capture d ecran 2016-08-02 a 14 37 39](https://cloud.githubusercontent.com/assets/3610253/17328690/687089b6-58bf-11e6-8826-7be58d8acb3a.png)
![capture d ecran 2016-08-02 a 14 42 20](https://cloud.githubusercontent.com/assets/3610253/17328691/68764efa-58bf-11e6-995c-9d69e37ea995.png)

**Comment by kvark** [comment]
Thanks for the report! I think I saw that on one of the older machines, but it definitely works correctly on the newer ones.

**Comment by Kerosene2000** [comment]
I have a macbook pro late 2013 on OS X El capitan.

**Comment by kvark** [comment]
I think I recall this problem now. TL;DR: GL sucks.
GL 2/3 doesn't have the query mechanism for the output target names from the shader. We desperately need that, since we match user provided targets with shader requirements.
We've got the new shader queries in (I believe them to be core in GL4), which work, but they are not supported on that OSX. Thus, the deferred pipeline is matching the targets blindly, and getting screwed up by the driver's GLSL compiler, which assigns unexpected slots to them (sorting alphabetically? idk).
One solution would be to use the explicit location, like here: `layout(location = output index) out vec4 outColor;`. I suspect this would only work for higher GLSL versions though, need to check.
Another (radical) solution is to finish Metal implementation (mostly done by @fkaa) and default to that on OSX.

**Comment by kvark** [comment]
Supposedly fixed by #1055
