### ISSUE TITLE
Int subtracting with overflow in the structure macro

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1017]
```
$ RUST_BACKTRACE=1 cargo run
    Finished debug [optimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/zoc`
thread 'main' panicked at 'attempt to subtract with overflow', <gfx macros>:17
stack backtrace:
   1:     0x55df38b4e51d - std::sys::backtrace::tracing::imp::write::h29f5fdb9fc0a7395
   2:     0x55df38b518b1 - std::panicking::default_hook::_{{closure}}::h17d8437f66223ab1
   3:     0x55df38b50aeb - std::panicking::default_hook::hbbe7fa36a995aca0
   4:     0x55df38b51178 - std::panicking::rust_panic_with_hook::h105c3d42fcd2fb5e
   5:     0x55df38b51012 - std::panicking::begin_panic::hbf62ea4a5ff3f9de
   6:     0x55df38b50f40 - std::panicking::begin_panic_fmt::h20f5943904e5791d
   7:     0x55df38b50ec1 - rust_begin_unwind
   8:     0x55df38b8ca6c - core::panicking::panic_fmt::h19323e466869c656
   9:     0x55df38b8c99b - core::panicking::panic::hbfac80217e56ecbe
  10:     0x55df38a573fc - _<visualizer..pipeline..Vertex as gfx..pso..buffer..Structure<gfx_core..format..Format>>::query::h51c2e08ea6fc136d
                        at /home/ozkriff/zoc/main/<gfx macros>:17
  11:     0x55df38a574c2 - _<visualizer..pipeline..pipe..Init<'a> as gfx..pso..PipelineInit>::link_to::h5b58b2f766031512
                        at /home/ozkriff/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-0.12.0/src/pso/buffer.rs:75
                        at /home/ozkriff/zoc/main/<gfx macros>:16
  12:     0x55df38a6f9eb - visualizer::context::new_pso::h4f950f2dce3d5f9f
                        at /home/ozkriff/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-0.12.0/src/factory.rs:171
                        at /home/ozkriff/zoc/main/src/visualizer/src/context.rs:39
  13:     0x55df38a76033 - visualizer::Visualizer::new::h152f2b3a1239f8dd
                        at /home/ozkriff/zoc/main/src/visualizer/src/context.rs:92
                        at /home/ozkriff/zoc/main/src/visualizer/src/lib.rs:62
  14:     0x55df38a3cda0 - zoc::main::h450465565f78cd5a
                        at /home/ozkriff/zoc/main/src/main.rs:6
  15:     0x55df38b50e17 - std::panicking::try::call::he2cac0ad48ff25a4
  16:     0x55df38b58f08 - <unknown>
error: Process didn't exit successfully: `target/debug/zoc` (signal: 6, SIGABRT: process abort signal)
```

Can be reproduced in debug mode with optimizations:

``` toml
[profile.dev]
opt-level = 2
```

**Comment by kvark** [comment]
cc @ozkriff @Vinatorul

**Comment by angered-ghandi** [comment]
I was able to reproduce this and get some additional information by adding some debug prints to gfx. It's happening because of subtraction on the integer value of an uninitialized pointer value, presumably to get the byte offset of a field inside of a struct:
https://github.com/gfx-rs/gfx/blob/873f689955ec50cb2caad88b1b02095b4ac7196e/src/render/src/macros/structure.rs#L55

This was on Windows 10 using stable rustc 1.12 (MinGW) in the debug build profile.

I modified that to look like:
```
                match sub_name {
                $(
                    $name => {println!("field: {}\nbase: {}\nbig_offset: {}", (&tmp.$field as *const _ as usize), base, big_offset); Some(Element {
                        format: <$ty as $compile_format>::get_format(),
                        offset: ((&tmp.$field as *const _ as usize) - base) as ElemOffset + big_offset,
                    }) },
                )*
```

Running this in my test program that repros the issue, it printed out:
```
field: 0
base: 0
big_offset: 0
thread 'main' panicked at 'attempt to subtract with overflow', <gfx macros>:28
```

This is odd because doing that same `(0 - 0) + 0` operation in the rust playground doesn't seem to repro the overflow:
https://is.gd/8tAJNy

When `tmp` (and thus, `base`) gets initialized to pointer value 0, the subtraction overflows. Seems like it might be better to initialize `tmp` to a known safe value, such as 1000 (arbitrary), so that overflow can never occur (or at least occur consistently so that it's easier to fix).

This is difficult to repro because you have to write a program in such a way that `tmp` happens to initialize to 0. I wasn't able to repro it on the triangle example, even after modifying it to behave like my test program. In triangle, `tmp` was always initializing to 152861056.

**Comment by angered-ghandi** [comment]
Weirder still, if I initialize tmp to a 0 pointer value explicitly, then the triangle example still runs just fine (no overflow):

Changing https://github.com/gfx-rs/gfx/blob/873f689955ec50cb2caad88b1b02095b4ac7196e/src/render/src/macros/structure.rs#L33 to:
```
                let tmp: &$root = unsafe{ std::mem::transmute(0usize) };
```

Interestingly, this doesn't fix it for my test program. Changing the subtraction to a `wrapping_sub` has resolved it (seemingly without ill effects), but I'm still curious why it overflows. I think the compiler may be doing something weird here.

**Comment by kvark** [comment]
Thanks @angered-ghandi, thats very helpful!
I think we should just pick the minimal address that is not NULL, so just "1" instead of `uninitialized`

**Comment by bluss** [comment]
Just quick note: sticking both uninitialized or 0 into a shared reference is undefined behavior, I mean, the actual pointer value is used immediately afterwards (cast to raw pointer), and that's not valid if you stuffed an invalid value in a primitive type (&T in this case).

**Comment by kryptan** [comment]
It overflows not when reference is zero but when it is instead initialized to some large value.
```Rust
let tmp: &$root = unsafe{ ::std::mem::uninitialized() };
```

if `tmp` gets set to something like `0xFFFF...` then `(&tmp.$field as *const _ as usize)` will be small non-negative number (this overflow is not detected) and then in `((&tmp.$field as *const _ as usize) - base)` large number is subtracted from the small one.
It shouldn't overflow when `tmp` is zero, I don't understand why it did for @angered-ghandi.
