### ISSUE TITLE
Consider using atomics instead of Mutex in the buffer handles

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1030]
Follow up to #1026 (cc @Bastacyclop)

**Comment by Bastacyclop** [comment]
For OpenGL I used `try_lock` because every API call is on the same thread, so if the user holds a mapping during submission we know it's an user error. However with backends like Vulkan mapping and submission can happen on different threads, so if the user holds a mapping during submission we don't know if it's an user error or if we simply need to wait the mapping release. That's why I think using `lock` is more sensible and I don't think atomics are suited to replace `lock`.
