### ISSUE TITLE
Dectect PSO component name collisions

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1042]
Something like this shouldn't be legal:

``` rust
pipeline pipe {
    vbuf: gfx::VertexBuffer<Vertex> = (),
    vr_left: gfx::RenderTarget<ColorFormat> = "pixcolor",
    vr_right: gfx::RenderTarget<ColorFormat> = "pixcolor",
    monitor: gfx::RenderTarget<ColorFormat> = "pixcolor",
}
```

cc @Bastacyclop @jaredr

**Comment by eugene2k** [comment]
I haven't even the slightest clue as to how to do it with rust's macros. Are you sure it's possible?

**Comment by Bastacyclop** [comment]
@eugene2k I don't think that you can do it with simple `macro_rules!`, but it should be easy with procedural macros / compiler plugins, we might need those for other features as well. I lost track of what is happening in that area, a new macro API should step in someday and make procedural macros a lot more attractive ?

**Comment by eugene2k** [comment]
Currently "Macros 2.0" is far from being stabilized and there's also work on the "Macros 1.1" api, which AFAIK only works for `#[derive()]` attributes. In other words, I don't think this bug is possible to resolve unless some sort of compiler/translator is added to gfx ecosystem to translate from DSL and into rust. Such a tool would probably solve [other problems with current PSO definitions](https://github.com/gfx-rs/gfx/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20pso).

**Comment by kvark** [comment]
I was wondering if something like an artificial `match` through these names in the macro-generated code would force Rust to ensure the arms (= names) are unique, even if the match result will be unused.

**Comment by eugene2k** [comment]
The error in that case would be "unreachable pattern", which would probably be very confusing.

**Comment by kvark** [comment]
not happened in pre-ll
