### ISSUE TITLE
Check OpenGL copy buffer capabilities

### ISSUE THREAD

**Issue by Bastacyclop** [gfx-rs/gfx#1131]
Follow up on #1129

**Comment by lxnt** [comment]
Here's a first take on this:

https://github.com/lxnt/gfx/commit/187872018adf5f70b2bba1fec6f9c6a6679156a2

A getter of all things, and relevant to only one backend at that, but replicated across all.
Couldn't think up anything better.

As for caps vs privcaps - I think caps such as this one, and `instance_call`, `separate_blending_slots`, `frame_buffer_support`, the nonexistent one for `glVertexAttribIPointer` should be exposed somehow. Otherwise the application code either blindly crashes or reimplements the capability detection.

PS. `clear_buffer_supported`/`glClearBufferfv` and friends do not have any corresponding extension, so that TODO should be just dropped.

**Comment by kvark** [comment]
@lxnt I think you are over-complicating this.
All that needs to be done for this issue is a flag in public `Capabilities` that tells if you can call `copy_buffer()`.

> As for caps vs privcaps - I think caps such as this one, and instance_call, separate_blending_slots, frame_buffer_support, the nonexistent one for glVertexAttribIPointer should be exposed somehow. 

`instance_call_supported` and `separate_blending_slots_supported` are already exposed in `Capabilties`.
`frame_buffer_support` and `glVertexAttribIPointer` are so marginal I don't think anyone cares about machines that don't support them. We can safely assume the user has these as a baseline. Remember: the main focus of gfx-rs is modern API compatibility.

> clear_buffer_supported/glClearBufferfv and friends do not have any corresponding extension, so that TODO should be just dropped.

Agreed.

**Comment by lxnt** [comment]
> @lxnt I think you are over-complicating this.
All that needs to be done for this issue is a flag in public Capabilities that tells if you can call copy_buffer().

Well, there were words of checking in the encoder.. But you are right. Here goes a PR.

**Comment by kvark** [comment]
Ah, right. Checking in the encoder and returning an error early would be nice. Now I see that your original code does that.

**Comment by lxnt** [comment]
Should I submit a PR with checks in the encoder?

If so, is the approach with cap getters in the Buffer trait acceptable, or there is some better way?

**Comment by kvark** [comment]
@lxnt I don't think we should have the public capability checks in both `Encoder` and `Capabilities`. Just the latter should be fine. The encoder needs to know about some of the flags, so that it can return an error if appropriate, but it doesn't need to have the flag getters.
Other than this little thing, yes, the PR would be nice!

**Comment by GabrielMajeri** [comment]
Is this issue still applicable? If so, where would the changes go?

> @lxnt I don't think we should have the public capability checks in both `Encoder` and `Capabilities`. Just the latter should be fine. The encoder needs to know about some of the flags, so that it can return an error if appropriate, but it doesn't need to have the flag getters.
> Other than this little thing, yes, the PR would be nice!

`Encoder` doesn't seem to exist anymore for OpenGL, where would be the right place to add these checks?

**Comment by kvark** [comment]
Thanks for triaging @GabrielMajeri ! I think this was for pre-ll, marking accordingly and closing.
