### ISSUE TITLE
Trouble enabling MSAA in cube example 

### ISSUE THREAD

**Issue by da-x** [gfx-rs/gfx#1186]
While trying to enable anti aliasing in the piston engine cube example I've narrowed the issue I've been having to GFX's own cube example.

Here is the attempt, along with the `apitrace` output:
https://github.com/da-x/gfx/commit/6c7935ee16c4a989a718b33ee91ffe3f605af3c1
(the `aa` branch under my `gfx` clone).

@kvark suggested I should post it. I have seen `GLX_SAMPLES = 4` in `glXChooseVisual` and `glXChooseFBConfig` under piston but not under this trace, but I am not sure which other function calls to look for in the GFX-only trace.

At any case, maybe its worth having an `gfx` example that enables AA.

**Comment by msiglreith** [comment]
To enable multisampling in gfx, you also need to enable multisampling for the backbuffer (the rendertarget in the cube example). Adding `with_mutlisampling(4)` at window creation (https://github.com/gfx-rs/gfx/blob/master/src/lib.rs#L122) works for me on Windows 10.

**Comment by kvark** [comment]
@da-x thank you for the report! Very nice to see the test code and an apitrace capture.

I cleaned up your code a bit and tried it on my side (https://github.com/kvark/gfx/commit/63e0dd7f3cb18b0e9b63635eee4daef6e46e1233). You are not seeing GLX_SAMPLES = 4 simply because you didn't change the app launcher to pass the MSAA parameters to glutin. You can see it in my code, and the anti-aliasing works as expected. Btw, no need to use the `draw_state` crate, since it's re-exported as `gfx::state`.

Since it works as expected here, the problem with piston lies elsewhere. I'm closing the issue, would be happy to help you investigate further on piston territory. cc @bvssvni 
If you could provide the code you are testing with, that would be great. Creating an issue in https://github.com/PistonDevelopers/gfx_graphics would help as well, assuming you use gfx-rs backend in Piston.

**Comment by kvark** [comment]
It might be as simple as enabling MSAA in the opaque PSOs that gfx_graphics creates, given that this will have no effect if the target FBO is not multisampled.

**Comment by da-x** [comment]
Thanks, I now verified that the Piston cube example works SDL2Window and multisampling. I'll probably send them a fix along with the cleanup.
