### ISSUE TITLE
How to use gfx with multiple threads?

### ISSUE THREAD

**Issue by torkleyy** [gfx-rs/gfx#1201]
Is there a way to do this? I'd like to use the `Factory` from multiple threads, however the one for OpenGL contains `Rc` which is not `Send`. I think OpenGL itself does not support multiple threads with the same context, does it? Is there anything implemented which uses a separate thread which dispatches all these events in order to support multi threading?

**Comment by Bastacyclop** [comment]
@torkleyy The OpenGL `Factory` contains `Rc` because, like you said, the OpenGL context is not thread-safe. However, you can fill multiple `Encoder`s with multiple threads before submitting them on the device thread.
You can look at https://github.com/kvark/pegasus.

**Comment by torkleyy** [comment]
@Bastacyclop Thanks for help. So what you are saying is that I cannot initialize buffers from multiple threads but only update / draw them?

**Comment by Bastacyclop** [comment]
More precisely, no OpenGL call can be performed outside of the device thread, even update and draw calls. Those OpenGL calls are performed by `Factory` and `Device` (so they are neither `Sync` nor `Send`). But you can still prepare those calls in advance by encoding commands with an `Encoder` so that they can be later executed as quickly as possible during submission to the `Device`. Update/copy and draw operations can be encoded this way on multiple threads, offloading the device thread from preparation work, but not from submission work. You cannot encode resource creations.

**Comment by torkleyy** [comment]
I do have another question:

If I implement a separate thread which holds the `Factory` and the `Device`, can I return `Buffer`s from that thread using channels? Because `Resources` requires `Buffer`s to be `Send`, so every backend should support that, right?

**Comment by Bastacyclop** [comment]
All the [resource handles](https://docs.rs/gfx/0.14.0/gfx/handle/index.html) are thread safe `Arc`s, so yes, you can safely share them between threads. The resources are released during `device.cleanup()` if you don't hold any references to them.

**Comment by torkleyy** [comment]
Thanks
