### ISSUE TITLE
Cube example renders differently with OpenGL vs Metal on MacOS

### ISSUE THREAD

**Issue by burtonageo** [gfx-rs/gfx#1204]
When rendering with Metal:

<img width="1136" alt="gfx_cube_example_metal" src="https://cloud.githubusercontent.com/assets/1732920/23586045/35972738-0185-11e7-993e-eeeb78d8c56c.png">

When rendering with OpenGL:

<img width="1136" alt="gfx_cube_example_opengl" src="https://cloud.githubusercontent.com/assets/1732920/23586053/462c7ca6-0185-11e7-98ca-51c562369a83.png">

<img width="582" alt="my_specs" src="https://cloud.githubusercontent.com/assets/1732920/23586062/7ce89e96-0185-11e7-8103-1a91e77e9d67.png">

**Comment by kvark** [comment]
Thanks for filing the issue! I wonder if we are confused here about `ARGB2101010` format. Seems rather unusual for a back buffer. Do you have HDR-enabled screen?

**Comment by eldyer** [comment]
Same problem here on my mac with NVIDIA GeForce GT 650M. Pixel depth is 32-Bit Color (ARGB8888).

**Comment by JohnColanduoni** [comment]
It looks like there are two issues (possibly with a single cause):

1. The single texel "texture" is being interpreted as BGRA event though gfx::format::Rgba8 is specified. The cube shows up as blue if you swap the blue and red in the cube's main.rs.
2. There's something funny going on with the gamma. Tweaking the format mapping in the metal backend by sending (Rgba8) to BGRAUnorm_sRGB at map.rs:241 (instead of BGRAUnorm) makes the background the right color, but the cube is still too dark.

My guess is this has something to do with the backend silently converting Rgba8 to Bgra8 for render targets, which we do to isolate the user from the fact that CAMetalLayers (i.e. the window) only supports BGRAUnorm, BGRAUnorm_sRGB and RGBA16Float. However Vulkan already requires the same juggling so we should probably stop doing the remapping.

**Comment by GabrielMajeri** [comment]
I think this was fixed by #1259 and can be closed.
