### ISSUE TITLE
Is it possible to keep support for OpenGL and use the new CoreLL?

### ISSUE THREAD

**Issue by siriux** [gfx-rs/gfx#1399]
I find the new CoreLL idea very interesting, but I would like to support OpenGL for a long time. Will it be possible to get the benefits of CoreLL and support OpenGL with a single implementation for the common parts?

I would like to know too if the high level abstraction will be supported in the future or only in the "classic" fork?

In short, it would really interesting to have a clear explanation of your picture for OpenGL and the high level API in the future, when CoreLL is stable.

Thanks !

**Comment by vitvakatu** [comment]
Hello, @siriux! I'm not professional in `gfx`, but I can say, that all backends (as OpenGL) will be supported in corell as well. CoreLL indroduces support for modern APIs (Metal, Vulkan, DX12), but it also supports backends that are available now. Missing features will be emulated.

**Comment by msiglreith** [comment]
We currently have 2 cores in the master `core` and `corell`. `corell` will only be 'temporary' (for several months..) and only support next-gen APIs. That's because we are in the process of integrating `corell` into out `core`. We already have merged new window system interface, queue support and much more. Alongside this process the OpenGL backend will be updated (and a vulkan and a dx12 backend for `core` added).
The final goal is to have *one* `core` with all backends, which looks similar to the current `corell`.

**Comment by siriux** [comment]
Thanks for your answers, that's reassuring.

**Comment by vitvakatu** [comment]
@siriux I think you can close this issue.
Join us on [gitter](https://gitter.im/gfx-rs/gfx) if you have more questions.

**Comment by kvark** [comment]
@siriux directly related - https://github.com/gfx-rs/gfx/issues/1539
