### ISSUE TITLE
[RFC] Pipeline definition semantics

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1429]
Here is how the old/current `gfx_pipeline` macro works:
  - it defines a pipeline *definition* in the form of 3 struct types: `Init`, `Meta`, and `Data`
  - when you create a pipeline *object* (PSO) by providing `Init`, the backend reflects all the inputs/outputs of the shaders and matches them against what the definition provides
  - `Meta` part is returned that opaquely contains all the routing from `Data` into the shader I/O slots
  - user provides `Data` for each draw call, which is routed via `Meta` in order to bind the slots

Biggest problem with this approach is that the resources need to be re-bound for *each* draw call. Actual resource layout can be different even between the same `Data` structs. We'd like to be able to bind resources in groups (welcome descriptor sets!) and independently of a used shader.

Conceptually, Vulkan calls this a "pipeline layout", and D3D12 has "root signature". When you create a PSO with these APIs, you provide the layout/signature with a requirement that it has to be compatible with shader I/O. So it's not derived from shader I/O, it's purely a validation thing to ensure shader compatibility. Our pipeline definitions should have exactly the same semantics.

Modifications needed to our macros:
  - have a separate block for descriptor set, which contains samplers, CBVs, SRVs, and UAVs.
  - have only the globals and descriptor sets in the main pipeline macro
  - output targets are really a part of a sub-pass definition of a render pass. The way these are defined is still TBD, but it's clear that they shouldn't be plain in the pipeline, given that there is a guaranteed single sub-pass that a pipeline is associated with (so we can pass it into the constructor directly, like the rasterized state).

Rough example:
```rust
gfx_descriptor_set!(DescSet {
    s_diffuse: gfx::Sampler = "s_Diffuse",
    t_diffuse: gfx::Texture<[f32; 4]> = "t_Diffuse",
});
gfx_pipeline!(pipe {
   dset: DescSet, // notice no names
   control: gfx::Global<u32>,
});
```

**Comment by msiglreith** [comment]
Thanks for starting the decision!
Current proposal looks like a solid starting point.

My current graphics pipeline descriptor for pipeline creation (WIP) looks like this
```rust
pub struct GraphicsPipelineDesc {
    /// Type of the primitive
    pub primitive: Primitive,
    /// Rasterizer setup
    pub rasterizer: s::Rasterizer,
    /// Shader entry points
    pub shader_entries: GraphicsShaderSet,

    /// Vertex buffers (IA)
    pub vertex_buffers: Vec<VertexBufferDesc>,
    /// Vertex attributes (IA)
    pub attributes: Vec<AttributeDesc>,

    /// Render target views (RTV)
    pub color_targets: Vec<ColorTargetDesc>,
    /// Depth stencil (DSV)
    pub depth_stencil: Option<DepthStencilDesc>,
}
```

Interesting here would be how to specify vertex attribute bindinds, color target data (blending)  and depth stencil state. As mentioned, blending and depth stencil depend on the associated subpass and match the attachment counts.
Therefore another point which we have to discuss is how to specify the renderpass definition due to strong coupling with pipelines.

Regarding pipeline layouts and descriptor sets, vulkan requires binding and locations to be set, which has to match the bindings/layouts in the SPIR-V modules.

I don't have a specific proposal _yet_ as there a quite a few dependencies between those definitions. We might want to enforce certain restrictions on the bindinds (e.g ascending without gaps), which would make things easier.

**Comment by kvark** [comment]
@msiglreith 
>My current graphics pipeline descriptor for pipeline creation (WIP) looks like this

Looks very much like [D3D12_GRAPHICS_PIPELINE_STATE_DESC](https://msdn.microsoft.com/en-us/library/windows/desktop/dn770370(v=vs.85).aspx) :)

> Therefore another point which we have to discuss is how to specify the renderpass definition due to strong coupling with pipelines.

I think we just need to define a pass separately as a sequence of sub-passes, and point to a sub-pass of it from the PSO descriptor, pretty much like Vulkan does. This would ensure the Portability layer to be thin. This is different from the current `color_targets`/`depth_stencil`.

> Regarding pipeline layouts and descriptor sets, vulkan requires binding and locations to be set, which has to match the bindings/layouts in the SPIR-V modules.

Right. I assumed we'll just assign them in an increasing order for the specified descriptor sets and vertex attributes. Might be better to have that explicit, given that the user has to put the same values in the shaders anyway...

**Comment by msiglreith** [comment]
> Looks very much like D3D12_GRAPHICS_PIPELINE_STATE_DESC :)

hah! Actually, a mix of our old PSO desc, d3d12 and mostly vulkan. Some points like logic operations and non-independent blending is an open issue.

> I think we just need to define a pass separately as a sequence of sub-passes, and point to a sub-pass of it from the PSO descriptor, pretty much like Vulkan does.

Agree. With strong coupling a meant that the pipeline desc needs to be compatible with the subpass passed on creation, so that we have a blend state for each attachment of the subpass (for independent blending). Even though it's not that high on the TODO list, an additional macro to define these blend and depth-stencil states might be interesting. Basically splitting our current pipeline into vertex buffers, layout and blend/depth/stencil-states.

> This would ensure the Portability layer to be thin

I might misunderstand that sentence, but these macros are in the render layer, therefore shouldn't affect our core api. Mainly exist for convenience and additional safety layer.

**Comment by Bastacyclop** [comment]
Relevant description from @kvark on gitter:
> First, I'd expect us to have a macro for describing a render pass "template": Vulkan supports pipelines used for "compatible" render passes, so we need that compatibility expressed at the type level, while the less important details are to be provided at render pass creation by the user (init/run time).
A render pass is a collection of sub-passes. We can probably start by having a single sub-pass, since it's what our current examples need anyway, and it will not involve sub-pass dependencies (but those are needed later on in any case).
>
> Then, we'd need a descriptor set declared by a macro. Basically, a block containing SRVs, UAVs, CBVs, and samplers.
> 
> Finally, the pipeline declaration should be specifying a render pass (as a template type) + sub pass that it can be used in, and the PSO components will be RTVs, DSVs, scissor, and descriptor sets

**Comment by kvark** [comment]
All the experiments with pipeline definitions in macros were fun but ultimately not a desired way forward.
