### ISSUE TITLE
OpenGL doesn't support constant specialization

### ISSUE THREAD

**Issue by ZeGentzy** [gfx-rs/gfx#2056]
The vulkan backend is rendering images too small. To make this more obvious, I've set the scaling factor in the vertex shader to 1 (no scaling) and changed the quad info to this:

POS X | POS Y | UV X | UV Y
-|-|-|-
-1 | 1 | 0 | 1
1 | 1 | 1 | 1
1 | -1 | 1 | 0
-1 | 1 | 0 | 1
1 | -1 | 1 | 0
-1 | -1 | 0 | 0

We should then expect to see the image touching the window's borders, and we do in the OpenGL backend, but in the vulkan one we don't. 

OpenGL on left, Vulkan on right.
![](https://i.imgur.com/jPFwbcV.png)
Short info header:
- GFX version:  #2052 and master
- OS: Linux
- GPU: 00:01.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Kaveri [Radeon R7 Graphics]

**Comment by grovesNL** [comment]
This seems like the correct behavior, due to the [the specialization constant](https://github.com/gfx-rs/gfx/blob/master/examples/hal/quad/main.rs#L218). The GL backend is missing quite a bit and doesn't support specialization constants yet, so it receives the default scaling factor set in the shader. In the other backends (Vulkan, Metal and DX12) the specialization constant provided in the PSO overrides the default scaling factor set in the shader.

If you set the specialization constant to `1.0` you should see them match in this case.

**Comment by ZeGentzy** [comment]
I was not aware of specialization constants, indeed, messing with it "fixes" the vulkan backend.

I imagine we could have the GL backend parse the SPIR-V code it receives and have it replace all the specialization constants with the value provided by pso:EntryPoint's specializations before passing it to spirv_cross. I'd be up for that task if you think that is the way to solve it.

**Comment by ZeGentzy** [comment]
So, I've looked at the c++ source for spirv-cross and adding specialization support could be done by creating a new class `GLSLSpecialCompiler` which publicly inherits from `GLSLCompiler`.  We would make the class normally. Then we'd iterate over all the ids (generated by the constructor), checking for every id if `ids[id].get_type()` equals `TypeConstant` or `TypeConstantOp`. If it equals the former then we check if `get<SPIRConstant>(id).specialization` is true and if so we update that value. If it equals the latter, well I don't think we support that judging from our code, but we could still update it. After we iterate other all the ids we can just treat it like normal again.

**Comment by ZeGentzy** [comment]
Fixed by #2057
