### ISSUE TITLE
How to properly make use of multiple windows?

### ISSUE THREAD

**Issue by svenstaro** [gfx-rs/gfx#2388]
Short info header:
- GFX version: 0.17
- OS: Arch Linux
- GPU: Intel

I'm obviously using multiple windows wrong but I can't for the life of me figure out where I'm actually doing something wrong. What I'm trying to do here is spawn multiple windows and basically just turn all of them a specific color. However, only one of them actually changes color.

I checked my references and everything but all looks good to me. There is no specific multi-window example for gfx so I'm resorting to an issue. My code is here:
https://github.com/svenstaro/wmfocus/blob/a2118958eae192ed2cd8cc37a67ac4ca4d673888/src/main.rs

**Comment by kvark** [comment]
Each window would have a separate GL context, which you need to [activate](https://docs.rs/glutin/0.18.0/glutin/trait.GlContext.html#tymethod.make_current) before rendering anything.

**Comment by svenstaro** [comment]
Oh, that works. There should definitely be an example/docs for this. If there are, I couldn't find them.

**Comment by kvark** [comment]
It's a rather specific use case, and also common knowledge about GL.
But yes, at least documenting this in gfx_window_glutin would help.

**Comment by siriux** [comment]
In addition to making the window context current before rendering to it, should we open the adapter (create a new device) for each window? Or is it possible/recommended to use a single device for all the windows?

**Comment by siriux** [comment]
Also, since this pull request https://github.com/gfx-rs/gfx/pull/2824/files it's not possible to make_current the context once you initialize the surface because the call consumes the context.

Does it mean we should handle each window from a different thread, and there is no option to handle all windows from the same thread?

Maybe make_current could be implemented directly on the Surface and Headless so that it can take the context out of the Starc and put it inside again after making it current.

**Comment by kvark** [comment]
@siriux note that the original issue was about pre-ll gfx-rs. Perhaps, you could file a new one? I'm going to close this in the meantime (we only keep around a few pre-ll issues that require patch fixes, if any).
