### ISSUE TITLE
Should be possible to downgrade QueueGroup and CommandPool

### ISSUE THREAD

**Issue by Benjamin-L** [gfx-rs/gfx#2476]
Currently `CommandBuffer` and `CommandQueue` have a function called `downgrade` which returns a struct with a lesser capability. I'm currently trying to write an abstraction over different sets of queue families, and having similar functionality for `QueueGroup` and `CommandPool` would make this much easier.

**Comment by kvark** [comment]
The current command pool API is weak. In order to be consistent, we need to remove the `Clone` bound from `CommandBuffer` type in gfx-hal (or make everything clone/copy-able, but that's a different and more controversial path). This would affect `CommandPool` more than anything else, so the API needs to be changed anyway.
If you can, I'd suggest to use the `RawCommandPool` for now.

**Comment by omni-viral** [comment]
FWIW, I use raw objects and roll my own abstraction which meets my requirements.

Notably it is hard to reuse recorded commands and working with individually resettable buffers is impossible with wrapper gfx-hal provides.

**Comment by kvark** [comment]
Not relevant any more as the typed layer got removed
