### ISSUE TITLE
Create a common device_type and vendor_id library for directx/gl/metal to use

### ISSUE THREAD

**Issue by jackmott** [gfx-rs/gfx#2602]
The recent additions of device_type inference and vendorid features to the GL  backend could be applied to dx11, dx12, and the vendor_id could be applied to metal.

Rather than repeating the code in each backend, could we put that code someplace all the backends can refer to?  It doesn't seem like hal is the right place for it though?

**Comment by jackmott** [comment]
Yes I think from Vulkan's point of view I believe that is what Integrated means, shared memory.  Can we discover that in DX 11/12?

If so that would definitely be better.  
Then maybe it would make sense for the vendor_id -> string mapping to exist in HAL, since that is actually a Vulkan thing.

**Comment by jackmott** [comment]
looks like in DX we can see if there is shared memory with this:
https://docs.microsoft.com/en-us/windows/desktop/api/dxgi/ns-dxgi-dxgi_adapter_desc

which we can get with this:
https://docs.microsoft.com/en-us/windows/desktop/api/dxgi/nf-dxgi-idxgiadapter-getdesc

I could try that out

**Comment by kvark** [comment]
Guessing the integrated/discrete based on the shared memory is not something we should do either. First, because, as I said, the user can see the available memory types themselves and make a call. Secondly, because even some discrete GPUs expose shared memory types (e.g. AMD Vega's 256MB pool). I'd say we don't make this more of a problem than it already is, and leave the complexity out of non-GL backends, if possible.

**Comment by jackmott** [comment]
ok I'll close this out.
