### ISSUE TITLE
Gfx getting started tutorial

### ISSUE THREAD

**Issue by jeancf** [gfx-rs/gfx#2712]
I discovered Gfx recently and I was completely sold on the concept but after spending 2 days poking around to try and put my first triangle on screen (unsuccessfully) I am ready to give up.

I am looking for a basic getting started kind of tutorial that would help build a minimalist app while explaining the fundamentals. However I searched and read enough to lead me to believe that such a thing may not exist.

I started with [Graphics by Squares: a Gfx-rs Tutorial](https://suhr.github.io/gsgt/) apparently inspired by [Learning Gfx](https://wiki.alopex.li/LearningGfx) that seems to have the right (i.e. low) level of complexity that I am looking for but it is unfortunately outdated. The API seems to have changed but I am unable to figure out what the new one is.

I also looked at this [Example](https://github.com/gfx-rs/gfx/tree/master/examples/quad) that seems great but with 800 lines of virtually uncommented code, it is hard to use for learning purposes.

Currently Gfx looks to me like a great place that I want to get into but of which I can't find the entrance. It is very frustrating. So I hope somebody can point me to something that can help me. If not, I hope that documenting my experience here can help contributors better understand the barrier to entry that currently exists.

Thanks!

**Comment by aleksijuvani** [comment]
@Lokathor has recently written a fairly comprehensive tutorial for gfx-hal [here](https://lokathor.github.io/learn-gfx-hal/01_introduction.html). It's peer reviewed to some extent and might provide a good starting point. The gfx-hal API closely mirrors Vulkan so any Vulkan learning materials will be useful also. Here are some documents that I've found useful in one way or the other:

* https://falseidolfactory.com/2018/08/16/gfx-hal-part-0-drawing-a-triangle.html
  (outdated, but it's still possible to follow with little effort)
* https://developer.nvidia.com/opengl-vulkan
  (specifically about the similarities and differences between OpenGL and Vulkan)
* https://developer.nvidia.com/vulkan-memory-management
  (an introduction to manual memory management on Vulkan)
* https://gpuopen.com/vulkan-device-memory/
  (memory management on AMD cards)
* https://vulkan-tutorial.com/
  (doesn't explain things very well, but provides solid Vulkan usage samples)
* https://software.intel.com/en-us/articles/api-without-secrets-introduction-to-vulkan-part-1
  (I haven't followed this series, but there are some good tidbits here and there)

It will also be in handy to keep the Vulkan documentation close-by and look at the documentation for the Vulkan equivalent of each gfx-hal function you're not familiar with, because they will have the same constraints.

**Comment by aleksijuvani** [comment]
I think another point of confusion here is that the tutorials you've been looking at are for the (now deprecated) gfx crate rather than the new gfx-hal crate that this repository now houses. This is explained to some extent [here](https://github.com/gfx-rs/gfx#the-gfx-crate). If you're looking to learn the new lower level gfx-hal API the resources I've linked above will be useful, but not so much for the older gfx crate.

**Comment by VitalyAnkh** [comment]
@aleksijuvani Can anyone familiar with gfx update the [learning gfx](https://wiki.alopex.li/LearningGfx) site?

**Comment by jeancf** [comment]
Aha, things start making more sense for me already :-)

Thanks a lot for the comprehensive answer! I will have a look at your pointers. Given that I was interested in the OpenGL/Vulkan abstraction, I will have a look at wgpu first.

**Comment by termhn** [comment]
@VitalyAnkh that is really just an article from one user of the old `gfx` and it is updated as far as I know for the latest version of the old `gfx` crate (or close enough that any differences would be relatively trivial to fix). As explained above, the `gfx` crate is NOT the same as the `gfx-hal` crate, which is what this repository now houses on the master branch.

**Comment by jeancf** [comment]
Maybe having a statement like "This Gfx crate is deprecated, please refer to Gfx-hal" in big bold letters on top of the github README page could prevent confusion. I had not noticed it until @aleksijuvani  mentioned it above.

**Comment by VitalyAnkh** [comment]
@termhn Oh I see. Thank you!

**Comment by termhn** [comment]
@jeancf Well, the main source of confusion is that gfx-hal is being developed in the same git repo (this one) that the old `gfx` crate was being developed in. Old gfx is now in the `pre-ll` branch. We have a [section](https://github.com/gfx-rs/gfx#the-gfx-crate) of the readme in this repo that explains this as well, in theory

**Comment by Lokathor** [comment]
Consider big bold letters on a line of its own at the top of the readme, before the graphic

**PLEASE BE AWARE: This Is Home To The `gfx-hal` Crate, The Old `gfx` Crate Is Now Deprecated**

Exact wording to be bikeshed

**Comment by kvark** [comment]
Added in 23408ba607ac36722e0cf21e9d8d928b25509ecd
