### ISSUE TITLE
Computing 

### ISSUE THREAD

**Issue by ShalokShalom** [gfx-rs/gfx#2761]
I found this project since I am looking for a solution to integrate cross platform computation. 
This seems valid. 
Do I see something that is actually different from reality, or why do you not promote it like that?

I can imagine lots of people to use this project for computation also.   

Vulkan Compute uses the same API as Vulkan for graphics, correct?
And gfx-rs available for all languages, yes?

**Comment by kvark** [comment]
We are not explicitly advertising it as "compute", but we aren't saying it's graphics-only either. The project name though implies graphics, and that's some historical baggage we got. It's partially addressed by wgpu-rs, which, as you can see, refers to GPU as a whole (assuming both compute and graphics).

Confusion aside, gfx-rs does provide computation facilities over Vulkan/Metal/DX12/DX11/other. It's not as powerful as OpenCL, but it can get a lot of good things done for sure. I can at least guarantee that Vulkan and Metal bits work, since I was running Vulkan CTS over us. Any issues in DX12/DX11/GL would be bugs for us to fix.

**Comment by ShalokShalom** [comment]
So why not popularise it as computation library?
What arguments count for graphics, which dont for computation?
I am asking, since I am currently trying to convince some people and they might ask. ;)

**Comment by kvark** [comment]
Well, what do you mean by "popularise"? We don't have a marketing department, and the dev resources we got are mostly spent on developing and testing the code. I consider the compute abilities we have to be implied in the context of gfx-rs. Feel free to help out by spreading the word about our mighty computing capabilities ;)

**Comment by ShalokShalom** [comment]
Simply spell it on the homepage.

**Comment by kvark** [comment]
@ShalokShalom would you want to make a more concrete proposal on how to spell it? Just replacing "graphics" to "graphics and compute" in the definition is enough?

**Comment by ShalokShalom** [comment]
I think so.

**Comment by kvark** [comment]
Fixed in 6d14a28e956664c502e8eb59397b6ba7e7e047ed
