### ISSUE TITLE
Cannot run quad example on macOS, it says "You need to enable the native API feature (vulkan/metal) in order to test the LL"

### ISSUE THREAD

**Issue by zheli** [gfx-rs/gfx#2774]
Short info header:
- GFX version: master@c4470d0298b9965bda01726a1c72996da068e3b1 
- OS: macOS Mojave 10.14.5
- GPU: Intel Iris Plus 655 (Macbook Pro 13" 2018 with touchbar)

I have installed XCode and try to run
`cargo run --bin quad --features metal`

However it always says 

> You need to enable the native API feature (vulkan/metal) in order to test the LL

**Comment by grovesNL** [comment]
Hi @zheli! This issue could be caused by running `cargo run --bin quad --features metal` from the `gfx` directory instead of the `gfx/examples` directory.

Is your working directory set to `examples`? For example, you should `cd examples` first as mentioned in the [examples readme](https://github.com/gfx-rs/gfx/tree/master/examples).

We could probably update the warning message to help with this in the future, if you'd like to send a pull request :)

**Comment by zheli** [comment]
Thx @grovesNL! Can't believe I made this simple mistake, haha. Completely missed the step to switch to `gfx/examples` folder. It works now!
