### ISSUE TITLE
gfx-backend-metal on PowerPC 64-bits little endian

### ISSUE THREAD

**Issue by leo-lb** [gfx-rs/gfx#3292]
Short info header:
- GFX version: v0.3.3
- OS: Fedora 32
- GPU: AMD WX7100

Build log:
```
error: failed to run custom build command for `gfx-backend-metal v0.3.3`

Caused by:
  process didn't exit successfully: `/tmp/grumpy_visitors/target/release/build/gfx-backend-metal-e7f9bcfb042160ad/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'unsupported target powerpc64le-unknown-linux-gnu', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-metal-0.3.3/build.rs:17:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: build failed
```

I am wondering what is architecture specific for this crate? I am trying to compile <https://github.com/amethyst/grumpy_visitors> and Amethyst showcase games used to work on my machine.

Thank you!

**Comment by grovesNL** [comment]
Hi! :wave: gfx-backend-metal is only meant to be compiled on macOS and iOS at the moment. The build script uses the Xcode Command Line Tools (xcrun) to build some built-in Metal shaders.

It looks like grumpy_visitors only tries to use the `metal` feature of Amethyst on `macos` targets (https://github.com/amethyst/grumpy_visitors/blob/62b71d366915e573ef124f958fce5338378ba80a/bins/client/Cargo.toml#L42) and otherwise defaults to `vulkan`. These features are forwarded to rendy to enable `gfx-backend-metal` (for `metal`) or `gfx-backend-vulkan` (for `vulkan`), see https://github.com/amethyst/rendy/blob/0e9e1501a88c26ba32974013d2cba965198fbe6d/core/Cargo.toml#L23

So maybe the `metal` feature is being passed somewhere for the target `powerpc64le-unknown-linux-gnu` but isn't supposed to be?

**Comment by leo-lb** [comment]
I see, well it's confusing because if I remove the https://github.com/amethyst/grumpy_visitors/blob/62b71d366915e573ef124f958fce5338378ba80a/bins/client/Cargo.toml#L42 section completely it does get further in compilation but fails with:
```
error[E0432]: unresolved import `amethyst::renderer::types::DefaultBackend`
  --> bins/client/src/main.rs:20:9
   |
20 |         types::DefaultBackend,
   |         ^^^^^^^^^^^^^^^^^^^^^ no `DefaultBackend` in `renderer::types`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `gv_client`.

To learn more, run the command again with --verbose.
```

Removing the section shouldnt change anything to the build result since that section shouldnt even be used on my platform AT ALL. So seems there's a bug in Cargo cfg handling in some situations or something, but I tested separately and it does work correctly.

Guess I'll close since this doesnt concern this project.

**Comment by kvark** [comment]
Cargo platform-dependent features are quite painful sometimes...
