### ISSUE TITLE
`DescriptorPool::allocate_set` doesn't use `max_sets` parameter on Metal backend

### ISSUE THREAD

**Issue by JoshuaLight** [gfx-rs/gfx#3476]
- GFX version: `gfx-backend-metal` _v0.6.4_
- OS: macOS Catalina _v10.15.7_
- GPU: Radeon Pro 560X

Hi. I'm trying to reuse a single descriptor pool for all uniform buffers, having the following code that creates the pool:
```rust
device.create_descriptor_pool(
    MAX_SETS,
    &[DescriptorRangeDesc {
        ty: DescriptorType::Buffer {
            ty: BufferDescriptorType::Uniform,
            format: BufferDescriptorFormat::Structured {
                dynamic_offset: false,
            },
        },
        count: 1,
    }],
    DescriptorPoolCreateFlags::empty()
)      
```

Here `MAX_SETS` is some number greater than `1` (e.g. `8` for `8` uniform buffers max).

However, it seems that Metal backend doesn't take the `max_sets` parameter into account: https://github.com/gfx-rs/gfx/blob/8bc6b8c0cf58cafbaad2af74d57c05001a6377d7/src/backend/metal/src/device.rs#L2027-L2035

As far as I understand, descriptors count and descriptor sets count are different things, but the emulated pool uses only descriptor ranges when calculating the available space.

Am I missing something here? Sorry, if this is a stupid question. The same code works correctly on Vulkan (though it failed when I used `1` as `max_sets`, trying to allocate more than `1` sets).

**Comment by kvark** [comment]
`gfx-rs` is an unsafe API, just like Vulkan is. If you create a pool with `max_sets = 1` but create more than one set from it - this is Invalid Use of the API, and technically UB. So Metal backend is in full right to just assume you are not allocating more sets than necessary, or just ignore `max_sets` if it doesn't need it.

**Comment by JoshuaLight** [comment]
> If you create a pool with max_sets = 1 but create more than one set from it - this is Invalid Use of the API, and technically UB

That's the behaviour I've observed on Vulkan. My situation was like that:
- pass `max_sets = 1` on Vulkan but create more than one descriptor set: got an error from Vulkan Validation Layers
- pass `max_sets = N` on Vulkan: works fine
- pass `max_sets = N` on Metal: backend panics with `FragmentedPool` error, because descriptor set pool doesn't have resources available (traces `available 0 samplers, 0 textures, and 0 buffers`, to be exact); found that Metal doesn't take into account the `max_sets` parameter

So, the question then is: what is the correct way to specify the maximum number of descriptor sets for the descriptor set pool with respect to both backends?

**Comment by kvark** [comment]
Let me clarify. If you pass `max_sets = N`, it's not a *guarantee* that you'll be able to allocate N descriptors. It's just a hint to the driver to tell the upper bound of what you expect to allocate.
The actual limit will be a subject to what descriptor set layouts (ranges) you are trying to get. Even if that totals up to numbers less than the descriptor ranges you passed at `vkCreateDescriptorPool`, the driver may still fail to allocate the descriptors if the pool got fragmented.

Going back to your original post and re-reading it, I think you are confused about the ranges in `create_descriptor_pool`. You think they define a layout of a descriptor set, which you will allocate N times. This is incorrect. These ranges are just what the pool will contain in total, and the `max_sets` is a separate limit on it. Nothing gets multiplied by `max_sets`.

Practically speaking, you probably want this instead:
```rust
device.create_descriptor_pool(
    MAX_SETS,
    &[DescriptorRangeDesc {
        ty: DescriptorType::Buffer {
            ty: BufferDescriptorType::Uniform,
            format: BufferDescriptorFormat::Structured {
                dynamic_offset: false,
            },
        },
        count: MAX_SETS,
    }],
    DescriptorPoolCreateFlags::empty()
)  
```
On that note, I think the issue is resolved. Happy to continue discussing it (and potentially reopen if needed)!
