### ISSUE TITLE
Debug markers in release build

### ISSUE THREAD

**Issue by fintelia** [gfx-rs/gfx#3482]
Right now, debug markers only available if the debug_assertions feature is set. This is true at least on the [Vulkan](https://github.com/gfx-rs/gfx/blob/f09b062c5159b4a9dd8879dff3c0a3ac1bd81ea7/src/backend/vulkan/src/lib.rs#L440) and [DirectX 12](https://github.com/gfx-rs/gfx/blob/f09b062c5159b4a9dd8879dff3c0a3ac1bd81ea7/src/backend/dx12/src/lib.rs#L751) backends, but I'd imagine the others as well. It would be nice if there were a feature flag or other way to enable debug markers in release builds as well.

**Comment by kvark** [comment]
Oh, fully agreed, this looks like an accidental bug in the backends. Would you want to make a PR to fix this?

**Comment by fintelia** [comment]
I took a look at this, but I'm not quite sure the best way to make backend features like this controllable to end users.

**Comment by kvark** [comment]
I think we should just make the Vulkan backend to *always* support debug markers, if it can, and ignore them otherwise (like it does today in release mode). We could roll out a `hal::Features` flag fro this, but I don't think it's necessary here, since debug markers are non-observable from the API side.
