### ISSUE TITLE
Implement Occlusion Queries

### ISSUE THREAD

**Issue by cmr** [gfx-rs/gfx#421]
See also, https://www.opengl.org/registry/specs/NV/conditional_render.txt

**Comment by csherratt** [comment]
Any ideas how this could be described as a command? I'm interested in doing some experiments that could be done using occlusions queries.

We need some way to model both the Query and the Conditional render. Both are very `stateful` as they require the opengl pipeline to be configured to write into it (in the case of the Query). Or read from it (in the case of conditions).

This could probably be added into the draw state.

`pub query: Option<Query>`
`pub condition: Option<QueryResult<Bool>>`

thoughts?

**Comment by kvark** [comment]
@csherratt I haven't been able to really play with queries, outside of standard usage. We need to understand the full spectrum of queries use cases. Thanks to @cmr information, we only need to care about occlusion queries as the lowest common denominator. Now, there is a couple of questions that I'd like to get answers/opinions for:

  1. Does stretching along multiple calls make sense for a query? In this case, having a `query` parameter to any call is impossible.
  2. Do overlapping queries make sense?

**Comment by csherratt** [comment]
> 1. Does stretching along multiple calls make sense for a query? In this case, having a query parameter to any call is impossible.

It is possible. You can for example query the number of ns in gpu time that your calls tool. That being said, there is a slight problem. `glBeginQuery` resets the query object to 0, meaning that you can't interleave query usage. So we will probably have to do something better then passing it into a parameter as a draw call.

> 2. Do overlapping queries make sense?
I believe you can overlap queries, as long as they are not measuring the same thing. So you can overlap a occlusion query, with a timing query.

I think we might need to do something that is more stateful then the current api in order to describe a query operation.

Maybe something like this
```rust
let query_result = render.query(|inner_renderer| {
    inner_renderer.draw(&(&batch, &data, &context), &frame);
    inner_renderer.draw(&(&other_batch, &data, &context), &frame);
});
```

This could get hairy of we start to follow this pattern in other places. A similar style could be used for frame targets for example.

```rust
render.with_frame(&frame, |inner_renderer| {
    inner_renderer.draw(&(&batch, &data, &context));
    inner_renderer.draw(&(&other_batch, &data, &context));
});
```

Which would mean mixing quarries and render would really drive up the tabstops.

```rust
let query_result = render.query(&frame, |inner_renderer| {
    inner_renderer.with_frame(&frame, |inner_most_renderer| {
        inner_most_renderer.draw(&(&batch, &data, &context));
        inner_most_renderer.draw(&(&other_batch, &data, &context));
    });
});
```

The other advantage to this style would be that you could call functions that used render via a trait.

```rust
fn some_draw_routine<R: Render>(r: &mut R) {
   /// do work
}

let query_result = render.query(&frame, |inner_renderer| {
    some_draw_routine(inner_render);
});
some_draw_routine(render);
```

**Comment by kvark** [comment]
> You can for example query the number of ns in gpu time that your calls tool.

Agreed, that's a good case for queries covering multiple draw calls.

> glBeginQuery resets the query object to 0, meaning that you can't interleave query usage.

Are you sure about that? I looked at the specification and found two interesting things:
  1. There is an active query per query target. Thus, it is possible to interleave queries of different targets.
  2. There is `glBeginQueryIndexed`, which allows multiple queries of the same target.

Thus, interleaving seems to be entirely possible... And hence the closure-based interface will not work here. I'm tempted towards just putting a state-full interface (similar to GLs) in, at least until we use it more and see if it could be done better without reducing the function.

**Comment by msiglreith** [comment]
Superseeded by https://github.com/gfx-rs/gfx/issues/1582
