### ISSUE TITLE
Implement texture swizzling

### ISSUE THREAD

**Issue by cmr** [gfx-rs/gfx#430]
https://www.opengl.org/registry/specs/ARB/texture_swizzle.txt

I guess this should be part of the `TextureInfo`

**Comment by ebaklund** [comment]
How do we want to think about this?

We do have swizzle as a part of the texture shader resource (format::Swizzle) but we could also set it up as part of the tex::SamplerInfo. However, Swizzle is **strictly** a OpenGL **texture** parameter and does not play well with the gfx Sampler abstraction. Another way of doing it is to make it a part of the tex::Descriptor.
Anyhow, I  suggest we use a nomenclature similar to  VkComponentSwizzle enums although that is very different than the existing formulation of format::Swizzle.

What do you think?

**Comment by kvark** [comment]
We can't have it in `SamplerInfo` since (as you mentioned), it's a texture parameter, not sampler one. So we just need to use that `format::Swizzle`, make it a part of the texture descriptor (used to create textures on the low level), and actually update the graphics backends to take it into account.

As for changing the nomenclature - I suppose it's just using R,G,B,A instead of X,Y,Z,W - I'd be totally fine with that change.

There is a problem though with adapting the type system for the texture views. The type of SRVs and UAVs currently is formed like this:
```rust
type View = $container< <$channel as ChannelTyped>::ShaderType >;
```
If we mix swizzling in, the `ShaderType` stays unchanged, but the `$container` is no longer valid - the swizzle makes everything accessible as 4-component container.

One of the radical ways to fix that is to remove the container entirely from the view type:
```rust
my_view: gfx::ShaderResource<f32> = "t_MyView"; // notice `f32` instead of some `[f32; 3]`
```
We can make sure the backend treats it compatible with the shader requesting any kind of container (`vec2`, `vec3`, `vec4`, or just a scalar).

**Comment by msiglreith** [comment]
Swizzling now in master. I don't think it's worth to add it for `pre-ll`.
