### ISSUE TITLE
Immutable/COW resource semantics

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#730]
(original idea by @csherratt)
Whenever a resource (or part of it) gets modified (`update_texture()`, `update_buffer()`, etc), we can check if the handle passed into the function is unique. If unique, we just modify the resource and return the same handle. If not unique, we copy the resource and return a new handle. This is basically COW on resources.

API-wise, this would require `&mut handle` as an argument to `update_*` calls instead of `&handle`. This will require 1) ensure uniqueness of the handle, and 2) allow the code to return a new handle.

The solution looks good on paper, but I can see problems with rather basic cases. For example, you have some meshes sharing a buffer, and you want to modify this buffer so that it affects the meshes. If you just modify the buffer, it will get copied (for no reason), and then you'll have to go through the meshes and assign the new buffer to them. So basically, you'll need to:
  - somehow extract the buffer first from all the meshes
  - make sure it's the only instance
  - update it
  - assign it back

This sounds difficult and impractical.

**Comment by csherratt** [comment]
I want to approach this as a pipeline correctness issue. Because we are using OpenGL as our current implementation the graphics drivers are doing quite a bit to make sure the command queue is going to create a consistent state. Doing buffer updates for example will create hidden barriers to avoid modifying a buffer that is inuse, even across frames. This is why buffer mappings can be problematic as the driver has to either proxy the mapping, or make sure that nothing is pending on the buffer.

This is a big problem once we start working on Vulkan backend. With vulkan we are basically given raw memory to play with. The barriers need to be injected by the our framework in order to insure correctness. This will be a nightmare to get correct.

Immutability solves this as none of the buffers will be updated if they have a pending command, or reference to it. To the API user this will look like everyone gets their own copy, but we won't have to store 1000 copies of that object in memory.

This explains why your example seems difficult. It assumes that the handle is a reference, where using Cow the handle behaves like a value. To update all the the handles at once just need one layer of indirection. ie. `Rc<RefCell<Handle>>` This is of course done by the api user, and not us. (well maybe gfx_scene).

**Comment by kvark** [comment]
@csherratt absolutely. Making a projection into Vulkan support helps a lot to understand the motivation.

About the level of indirection - we'd have it in the `render` module, since each of the mesh attributes refers to a buffer...

**Comment by csherratt** [comment]
With `Mesh` we are in a difficult position. A mesh suddenly becomes a value too, which breaks many of the assumptions people have been making. So our api users would have to basically rebuild a mesh each time if they wanted to modify a mesh's vertices. Ew.

**Comment by kvark** [comment]
@csherratt right. I wonder if we should just re-architecture the mesh as a concept. Related to #640

**Comment by csherratt** [comment]
There are other options. I said it would be nightmarish to figure out the correct barriers, but on second thought I'm not sure I am correct. We could embed two counts into each Handle, one for the user references, and one for the command references. If there is a command pending with a reference to a buffer `gfx-rs` could either block, or return an failure result so that the user knows they need to handle this issue in another way.

This is pretty much the same idea as immutability, but the rules only apply when a buffer is shared between the command queue and the api user.

This still might be difficult to get right from the user perspective. But it can be left as problem that the user needs to solve, rather then one we try to solve for them. We might give them tools to help, COW could still be done even if it was not the default.

**Comment by csherratt** [comment]
I have come to the conclusion that this is a feature for a higher level library then `gfx-rs`.
