### ISSUE TITLE
Use runtime information for texture format instead of generics

### ISSUE THREAD

**Issue by bvssvni** [gfx-rs/gfx#851]
The new design looks better, but in my opinion the part concerning texture formats could be improved.

Currently, `Factory::create_texture_const` has the following definition:

```rust
fn create_texture_const<T: format::TextureFormat>(
    &mut self,
    kind: tex::Kind,
    data: &[<T::Surface as format::SurfaceTyped>::DataType],
    mipmap: bool
) -> Result<(handle::Texture<R, T::Surface>,
    handle::ShaderResourceView<R, T::View>), CombinedError>
```

`TextureFormat` has the following definition:

```rust
pub trait TextureFormat: Formatted { }
```

This trait has an auto impl.

To create an rgba8 texture, you pass in the raw data `data: &[<T::Surface as format::SurfaceTyped>::DataType]` which is a fancy generic for `&[u8]`.

We know that Rust does not infer the format from `u8` alone. A generic parameter is required.

So, in order to know what you can pass in, you might search for `Rgba8` and find this type alias (or you might figure out that from the triangle example):

```rust
type Rgba8 = (R8_G8_B8_A8, Unorm);
```

It works because the auto impl of `TextureFormat` is based on `Formatted` which is implemented for `(R8_G8_B8_A8, Unorm)`.

When the method returns successfully, it returns two objects `(handle::Texture<R, T::Surface>, handle::ShaderResourceView<R, T::View>)`.

The last one is a phantom type/empty struct. I guess this is for some type checking in the pipeline.

In Piston, we have a gfx_texture library that creates textures, while the pipeline is defined in gfx_graphics. I guess `ShaderResourceView` must be constructed manually.

The triangle example does not use the texture, it uses the `texture_view`. It is a phantom type! When is the texture handle freed from memory? The only way I can imagine this working is that the OpenGL backend binds the texture when creating it, and then the memory is leaked.

I wondered what the second generic parameter `S` on `Texture<R, S>` was and after a digging for hours I finally figured out it should be the phantom type `R8_G8_B8_A8`. Hmm.... that's wrong too, because it seems to be `Rgba8` when I look over my notes.

### Problems

1. It is a pretty long chain of inference before you get to the bottom of how it works
2. The API requires you to fill out generic parameters :cry:

### Questions

1. What if you have a more than one texture formats, but one pipeline?
2. What is the consequence of monomorphizing all these methods?
3. Does the triangle example leak the texture memory?
4. What is `ShaderResourceView` doing?

### Suggestions

- Create an `enum CreateTexture<'a>` that contains all you need for creating a texture, one variant for each texture format
- Use constructors for statistically common cases, for example `CreateTexture::rgba8(&img)`
- Use builder methods to customize the creation
- Move texture format to runtime, such that you have one concrete type per backend

You do not have to sacrifice type safety, because the `CreateTexture` constructors can handle that. There are also ways builder methods can be implemented only when using the right constructor. This will only be used to call `Factory::create_texture`.

Perhaps we could learn a bit from Conrod here. It also has a very complicated model under the hood, but it is easy to use because of builder methods.

I would like to create textures independently of the pipeline. This might lead to a runtime error, but I think it is worth it getting rid of some of the generics.

**Comment by kvark** [comment]
Such a detailed issue, wow... Thanks for showing us the good example!

> To create an rgba8 texture, you pass in the raw data data: `&[<T::Surface as format::SurfaceTyped>::DataType]` which is a fancy generic for `&[u8]`.

This is wrong, and I was going to talk to you about it. `DataType` for `Rgba8` is actually `[u8; 4]`, as you would expect. Hence, the examples use `cast_slice` hack to load images from piston-image. What I'd like to request from this library is to actually provide the image data as a slice of pixels, where a pixel is `[u8; 4]` for rgba textures.

> The last one is a phantom type/empty struct. I guess this is for some type checking in the pipeline.

It's not an empty struct. It's an SRV handle, which has the backend's view as well as holds the original object by `Arc` too. It is needed for any usage of the texture in the shaders. In fact, typically you can throw away the texture itself (the first argument), if you never want to change it and just want to bind it. The SRV handle will hold it alive anyway.

> So, in order to know what you can pass in, you might search for `Rgba8` and find this type alias.

It's not the only format that you can pass in. Anything (as in - any legal format) that is compatible with the data type should work.

> I guess `ShaderResourceView` must be constructed manually.

I see no problem for `gfx_texture` to construct it automatically.

> When is the texture handle freed from memory?

All the views (SRV, UAV, RTV, DSV) hold the original source (typically a texture object). Look at the handle definitions:
```rust
enum ViewSource<R: Resources> {
    Buffer(Arc<R::Buffer>),
    Texture(Arc<R::Texture>),
}
pub struct RawShaderResourceView<R: Resources>(Arc<R::ShaderResourceView>, ViewSource<R>);
pub struct ShaderResourceView<R: Resources, T>(RawShaderResourceView<R>, PhantomData<T>);
```

> Hmm.... that's wrong too, because it seems to be Rgba8 when I look over my notes.

I'm sorry about your wasted time. We definitely need some documentation on the universal format spec! Here is in short the way it works, applied to textures:
  - a texture itself is just a storage of pixel data. Views for it are created independently and allow binding it to the shader for sampling (SRV) or writing (UAV), or as a render target (RTV, DSV).
  - thus, texture is typed by the surface format. It's `format::SurfaceType` at run-time, or a phantom implementing `format::SurfaceTyped` at compile time, with the same name. In DX world, these are called "typeless" formats, because they only specify the bits per component and not the way they are interpret.
  - The interpretation comes from the `ChannelType` (implemented as well on both run-time and compile-time levels). Together they form `format::Format` (at run-time, or a phantom implementing `format::Formatted` at compile-time). `Formatted` is implemented automatically for `(S,C)` if `S: SurfaceTyped` and `C: ChannelTyped`. That's why `type Rgba8 = (R8_G8_B8_A8, Unorm);`
  - So, for a rgba texture, the texture object itself will be typed with `R8_G8_B8_A8`. The full type is needed for `create_texture_const` because it gets translated into run-time and used to specify the exact way you want to interpret the texture contents for the view (which is returned alongside).
  - This full type is not needed to be present as a phantom parameter of anything, because the view only cares about the end represented type (which is both `[f32; 4]` for, let's say, `Unorm`- and `Float`-channeled views).

> It is a pretty long chain of inference before you get to the bottom of how it works

Yes, I understand, there is plenty of generics and associated types. Keep in mind that this stuff has been through a couple of iterations already. Once you understand, it looks beautiful: it has everything required for safe abstractions, and nothing over it.

> The API requires you to fill out generic parameters

I tried to address this, however ended up precisely with the need, and I'll try to explain. See, for this `create_texture_const` method, we can't derive the generics from the input. We can't even derive them from the output, as I explained above. We could pass more arguments in, some - just to specify the types, but then - for cases where we know the target format, we'd need to somehow instantiate it into these parameters, which involves default constructors for non-longer-phantom types and other nasties. I figured that the current solution is simpler. There is no redundant information in the call that specifies a generic parameter, it's just a little not so hot looking, perhaps.

> What if you have a more than one texture formats, but one pipeline?

A pipeline can use a texture in multiple ways. If we are talking about SRVs, then we may have different formats (say, `T1` and `T2`) for textures bound to the same PSO input (at different times, of course) for as long  `T1::View == T2::View`, because that's what PSO SRV input is typed with:
```rust
color: gfx::TextureSampler<[f32; 4]> = "t_Color", // [f32; 4] is the associated type for `Rgba8::View`
```

> What is the consequence of monomorphizing all these methods?

Dunno. Could you reword the question?

> Does the triangle example leak the texture memory?

No, it should not.

> What is `ShaderResourceView` doing?

It's an SRV. The same `R32` (this is the surface format) texture, for example, can be viewed as `f32` (corresponding `Float` channel type) or as `u32` (corresponding `Uint` channel type). So you can have multiple views of the same texture, potentially with different types. The views are what shader needs, so they are inputs of some PSO components.

> Suggestions

We could just have a couple of methods in `FactoryExt`, like we used to: `create_texture_rgba8` and similar.

> You do not have to sacrifice type safety, because the `CreateTexture` constructors can handle that. 

But then you'd not be able to enforce PSO binding safety at compile time...

> I would like to create textures independently of the pipeline. This might lead to a runtime error, but I think it is worth it getting rid of some of the generics.

Let me repeat if this wasn't clear. Textures ARE created independently of the pipeline.

Moreover, if you don't want to deal with texture generic types - just use the raw versions of them! Creation of textures and views is fully provided on this lower level by the `Factory` trait. On PSO side you'll either need to (unsafely) wrap your raw texture into a phantom (`InnerRaw` as you name it) that PSO expects, or roll in a special PSO component for raw textures.

Mind you, I was going to introduce the "raw" version of the `VertexBuffer` component, and even weakly-typed PSO. So a raw texture component will feel itself quite comfortable there ;)

**Comment by bvssvni** [comment]
OK, this made stuff clearer. Can you open up an issue on the image repo about `[u8; 4]`?

I'll close this.

**Comment by kvark** [comment]
Here you go: https://github.com/PistonDevelopers/image/issues/509

**Comment by kvark** [comment]
Related - #853
