### ISSUE TITLE
Add `SurfaceType::has_alpha`

### ISSUE THREAD

**Issue by bvssvni** [gfx-rs/gfx#858]
http://gfx-rs.github.io/gfx/gfx_core/format/enum.SurfaceType.html

This can be used enable/disable alpha blending for optimization.

**Comment by kvark** [comment]
A couple of notes:
1. We need to make it more general than just `has_alpha`. Perhaps, change `get_bit_size` return type to `[u8; 4]` so that each component can be inspected separately.
2. Strictly speaking, the surface type doesn't have anything to do with "alpha", since it's just the allocation. When swizzling is supported, it is what defines the alpha channel - it can be pointing to one of the surface channels (even R/G/B, not just A), or it can be a constant 0/1. We don't have full swizzling support yet.
