### ISSUE TITLE
Better PSO initialization errors

### ISSUE THREAD

**Issue by sectopod** [gfx-rs/gfx#896]
Currently what I get is `DescriptorInit(some_id, some_option)`. It would be great to at least return the name of the thing that's getting not found or mismatched. Problem is - we'd optimally want to borrow these names from `ProgramInfo` instead of cloning them in order to avoid heap allocation. However, some of the PSO constructors in `src/render/factory.rs` are linking the program inside them, so they can't return anything out that's bound to the program lifetime...

Perhaps, we could use `Cow<str>` there? Getting understandable errors here is extremely important to assist people debugging their code.

**Comment by kvark** [comment]
After some thinking I figured that the best way would be to have something like `PsoError<S>`, where `S = &'a str` when passing the program handle (no allocations!), and `S = String` otherwise. Some boilerplate is required to convert between `PsoError<&'a str>` to `PsoError<String>` but otherwise should be efficient and ergonomic.
