### ISSUE TITLE
Reconsider where `update_texture` and `update_buffer` should live

### ISSUE THREAD

**Issue by sectopod** [gfx-rs/gfx#897]
Currently they are a part of the `Factory` trait. However, in DX11 the corresponding `UpdateSubresource` is a method of the immediate context, which is represented by our `Device`. Obviously, requiring the device for resource updates may be less convenient for the end users, but we need to check other APIs (Vulkan, Metal, DX12) to see what's the best place for these methods.

**Comment by kvark** [comment]
- DX11: via the immediate context, not the device (in DX terms): [UpdateSubresource](https://msdn.microsoft.com/en-us/library/windows/desktop/ff476486%28v=vs.85%29.aspx)
- DX12: via the command list (essentially similar to DX11): [UpdateSubresouces](https://msdn.microsoft.com/en-us/library/windows/desktop/dn899212%28v=vs.85%29.aspx)
- GL: via the same GL context: [glTexImageXD](https://www.opengl.org/wiki/GLAPI/glTexImage2D)
- Metal: via the texture object directly: [replaceRegion](https://developer.apple.com/library/prerelease/ios/documentation/Metal/Reference/MTLTexture_Ref/index.html#//apple_ref/occ/intfm/MTLTexture/replaceRegion:mipmapLevel:slice:withBytes:bytesPerRow:bytesPerImage:)
- Vulkan: no explicit update function, only memory mapping: [vkMapMemory](https://www.khronos.org/registry/vulkan/specs/1.0/man/html/vkMapMemory.html)

**Comment by kvark** [comment]
So, it doesn't look like we need to change the API here. The key point to the solution is simply not to use `UpdateResource` for the `Factory::update_*` methods, and use it only for the `CommandBuffer::update_*` implementations.

One thing that's not clear yet, is to how we are going to implemente `CommandBuffer::update*` calls for Vulkan. It seems to me that map/unmap is the only way to go there, but it requires `vkDevice`, which we'd optimally want to only be owned by a factory. However, we don't know what else is going to be needed for the command buffer execution, so we may just end up including `vkDevice` into both the factory and the device.

**Comment by sectopod** [comment]
There appear to be problems with this approach. `UpdateSubresource` works on `Default` usage textures (our name is `GpuOnly`), while map/unmap requires dynamic or staging usage. For some types, like cube maps, dynamic usage is not even possible.

**Comment by kvark** [comment]
Hmm, in this case we might want to remove these methods entirely from the Factory interface. Old use-cases could be split in three groups:
  1. Calling create_texture_with_data
  2. Mapping/Unmapping manually. This can be nice for saving memory, if we can read the image directly into the mapping region without allocation. Cc @bvssvni
  3. Updating via the command buffer during rendering, not necessarily each frame. Again, we could save some allocations if we return the mutable slice inside our data buffer instead of just copying stuff there.

UpdateSubresource then would still be used as an implementation detail for resources created with GpuOnly usage.

A good side effect of the removal of these methods is: less variety of methods to update stuff means less confusion for the user, especially when mixing direct updates with command buffer ones.

Hope this makes sense and helps!
